#        Array Arithmetic on Numpy

In [1]:
import numpy as np

Let’s create two NumPy arrays to showcase their usefulness

In [2]:
np_a = np.array([9,8,7,6,5,4,3,2,1])
np_b = np.array([1,2,3,4,5,6,7,8,9])
np_c = np_a-np_b

In [3]:
np_c

array([ 8,  6,  4,  2,  0, -2, -4, -6, -8])

Subtracts the corresponding index value from both numpy array and  stores result in c variable

In [4]:
np_c = np_a + np_b

In [6]:
np_c

array([10, 10, 10, 10, 10, 10, 10, 10, 10])

Adds the corresponding index value from both numpy array and  stores result in c variable

<img alt ="Visuals of Numpy addition"  src = "Images\Numpy_addition.PNG" >

In [7]:
np_e = np_a**np_b
np_e

array([   9,   64,  343, 1296, 3125, 4096, 2187,  256,    1], dtype=int32)

<strong>Note:</strong>Example 4**5 => a^5

In [8]:
np_f = np_a*5
np_f

array([45, 40, 35, 30, 25, 20, 15, 10,  5])

<img alt ="Visuals of Numpy arthimetic"  src = "Images\Subtract.jpg" >

There are often cases when we want to carry out an operation between an array and a single number (we can also call this an operation between a vector and a scalar). Say, for example, our array represents distance in miles, and we want to convert it to kilometers. We simply say data * 1.6:

<img alt ="Visuals of Numpy arthimetic"  src = "Images\Broadcasting.JPG" >

See how NumPy understood that operation to mean that the multiplication should happen with each cell? That concept is called <strong>broadcasting</strong>, and it’s very useful.

# Aggregation functions

In [10]:
print(np_c.max()) # similarly max element of array

10


Finds the max element out of matrix

In [11]:
print(np_c)
np_c.sum() # sum of all element

[10 10 10 10 10 10 10 10 10]


90

In [13]:
print(np_e)
np_e.min()

[   9   64  343 1296 3125 4096 2187  256    1]


1

<img alt ="Visuals of Numpy arthimetic"  src = "Images\aggregate.JPG" >


# Matrice Creation

We can pass python lists of lists in the following shape to have NumPy create a matrix to represent them:
<img alt ="Visuals of Numpy arthimetic"  src = "Images\Matrix_creation.JPG" >

We can also use the same methods we mentioned above (ones(), zeros(), and random.random()) as long as we give them a tuple describing the dimensions of the matrix we are creating:

<img alt ="Visuals of Numpy arthimetic"  src = "Images\matix_multi.JPG" >

In [14]:
arr1 =  np.arange(10).reshape(5,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
arr2 = np.arange(0,30,3).reshape(5,2) 
arr2

array([[ 0,  3],
       [ 6,  9],
       [12, 15],
       [18, 21],
       [24, 27]])

(0,30 is range and 3 is value of stepsize)

In [16]:
arr3 = arr1+arr2
arr3

array([[ 0,  4],
       [ 8, 12],
       [16, 20],
       [24, 28],
       [32, 36]])

In [17]:
np_arr = arr3 + np.array([1,10])
print(np_arr)

[[ 1 14]
 [ 9 22]
 [17 30]
 [25 38]
 [33 46]]


We can get away with doing these arithmetic operations on matrices of different size only if the different dimension is one (e.g. the matrix has only one column or one row), in which case NumPy uses its broadcast rules for that operation:

<img alt ="Visuals of Numpy arthimetic"  src = "Images\matix_add_broad.JPG" >


In [18]:
arr4 = arr1*arr2
arr4

array([[  0,   3],
       [ 12,  27],
       [ 48,  75],
       [108, 147],
       [192, 243]])

In [19]:
arr5 = arr2**3
arr5

array([[    0,    27],
       [  216,   729],
       [ 1728,  3375],
       [ 5832,  9261],
       [13824, 19683]], dtype=int32)

Remember in above example we are doing power of each element to 3

A key distinction to make with arithmetic is the case of <a href= "https://www.mathsisfun.com/algebra/matrix-multiplying.html" >matrix multiplication</a> using the dot product. NumPy gives every matrix a dot() method we can use to carry-out dot product operations with other matrices:

<img src = "Images/dot.JPG">

In [20]:
arr6 = arr1.dot(arr2.reshape(2,5)) # dot product of 2 numpy array
arr6

array([[ 15,  18,  21,  24,  27],
       [ 45,  60,  75,  90, 105],
       [ 75, 102, 129, 156, 183],
       [105, 144, 183, 222, 261],
       [135, 186, 237, 288, 339]])

# Transposing and Reshaping

A common need when dealing with matrices is the need to rotate them. This is often the case when we need to take the dot product of two matrices and need to align the dimension they share. NumPy arrays have a convenient property called T to get the transpose of a matrix:

<img src = "Images\Transpose.JPG">

In more advanced use case, you may find yourself needing to switch the dimensions of a certain matrix. This is often the case in machine learning applications where a certain model expects a certain shape for the inputs that is different from your dataset. NumPy’s reshape() method is useful in these cases. You just pass it the new dimensions you want for the matrix. You can pass -1 for a dimension and NumPy can infer the correct dimension based on your matrix:

<img src = "Images\Reshape.JPG">

In [21]:
arr7 =  np.arange(20).reshape(5,4)
arr7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
arr7.T # to get the transpose of numpy array

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

# Matrix Aggregation
Not only can we aggregate all the values in a matrix, but we can also aggregate across the rows or columns by using the axis parameter:

<img src = "Images/matrix_aggregate.jpg" >


In [23]:
arr = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]]) 
arr.min(axis = 0) # finds the minimum array element among axis = 0, means column wise

array([1, 1, 2])

In [24]:
arr.sum(axis=1) # finds the sum along axis = 1, means row size

array([12, 13, 13])

The way the axis is specified here can be confusing to users coming from other languages. The axis keyword specifies the dimension of the array that will be collapsed, rather than the dimension that will be returned. So specifying axis=0 means that the first axis will be collapsed: for two-dimensional arrays, this means that values within each column will be aggregated.

In [25]:
arr.cumsum(axis = 1) # cummulative sum along the rowwise

array([[ 1,  6, 12],
       [ 4, 11, 13],
       [ 3,  4, 13]], dtype=int32)

In [26]:
np.sqrt(arr)

array([[1.        , 2.23606798, 2.44948974],
       [2.        , 2.64575131, 1.41421356],
       [1.73205081, 1.        , 3.        ]])

In [27]:
a = np.array([10, 40, 80, 50, 100]) 
print(a[a%40==0]**2) 

[1600 6400]
