In [25]:
import numpy as np


# Slicing/Indexing of numpy
We can index and slice NumPy arrays in all the ways we can slice python lists:

In [26]:
number = np.arange(0,48,2).reshape(2,3,4) # getting 3-d array with 2 rows, 3 col, 4 with 3rd dime
number

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[24, 26, 28, 30],
        [32, 34, 36, 38],
        [40, 42, 44, 46]]])

In [27]:
number[:,:,0] # number(martix,row,coln),
# from both matrix and all rows just select the first column

array([[ 0,  8, 16],
       [24, 32, 40]])

number(martix,row,coln), from both matrix and all rows just select the first column
":" means all values of that dimesnion,like in last example....we are trying to slice last column of both matrix. Now if you want to get only from the first matrix then you could do something like :-- number[0,:,
<img src= "Images/three_dimension_numpy_array.PNG">

<img src = "Images/Indexing.jpg">

In [28]:
number[:,-1,-1]

array([22, 46])

In [29]:
number[0,:,-1] 

array([ 6, 14, 22])

In above example we are trying to get last column elements from first dimension matrix 

In [30]:
arr4 = np.arange(32).reshape(2,4,4)
arr4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [15]:
arr4[[[0,1,1,1],[3,2,1,0],[0,2,1,3]]] # we can have Array Indexing as well

c:\users\animeshs\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([12, 26, 21, 19])

In [31]:
# Boolean based indexing, based on condition also we can get the value
condition = arr4>5
arr4[condition]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31])

In above example, arr4>5 will store one array with bool vlaues like True and False.  True for when condition is true that is when element of arr4 is greater than5. and when pass that array, all true position index value will get printed

In [32]:
arr5 = np.arange(12).reshape(4,3)

In [33]:
arr5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
row = np.array([[0,0],[2,2]])
col = np.array([[1,1],[2,2]])
arr5[row,col] # Similar thing could be done by this as well x[[0,2],0:2]   [1:4,[1,2]] @ and [...,1] 

array([[1, 1],
       [8, 8]])

In above example we are passing the custom array that would work as indixing in numpy

In [24]:
arr6 = np.array([1,0,2,3,4,0,5,6,8])
arr6.nonzero() #to get the non-zero indexes

(array([0, 2, 3, 4, 6, 7, 8], dtype=int32),)

In [25]:
arr6_copy = np.copy(arr6) # to coppy numpy array to refrence later
arr6_copy

array([1, 0, 2, 3, 4, 0, 5, 6, 8])