In [3]:
import numpy as np


# Slicing/Indexing of numpy

In this section we will look at indexing and slicing. These work in a similar way to indexing and slicing with standard Python lists, with a few differences.
We can index and slice NumPy arrays in all the ways we can slice python lists:

Indexing is used to obtain individual elements from an array, but it can also be used to obtain entire rows, columns or planes from multi-dimensional arrays.

In [4]:
a1 = np.array([1, 2, 3, 4, 5])
b = a1[1:4]  # SYNTAX - numpy_array[startindex:endIndex]
print(b)

[2 3 4]


The only thing to remember if that (unlike a list) a1 and b are both looking at the same underlying data (b is a view of the data). So if you change an element in b, a1 will be affected (and vice versa):
<br></br>
<strong> Note: </strong> You will be wondering why it didn't take the 4th element as we have mentioned as endIndex but while slicing <strong> List and Numpy</strong> exclude the endIndex item. It gives till endIndex-1 item

In [8]:
b[1] = 10
print(b)
print(a1)

[ 2 10  4]
[ 1  2 10  4  5]


If you see we changed the element of b[1] and the value refelected in a1 as well.

We can index into this array to get an individual element, exactly the same as a normal list or tuple:

In [10]:
print(a1[0]) # 1
print(a1[2]) # 10

1
10


# #Numpy Indexing
 We can create a 2 dimensional numpy array from a python list of lists, like this:

In [13]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<img src = "Images/indexing_ij.JPG">
We can index an element of the array using two indices - i selects the row, and j selects the column:

In [14]:
print(a2[2, 1])

8


Notice the syntax - the i and j values are both inside the square brackets, separated by a comma (the index is actually a tuple (2, 1), but tuple packing is used). The example picks row 2, column 1, which has the value 8. This compares with the syntax you might use with a 2D list (ie a list of lists):

In [16]:
v = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

print(v[2][1]) # 8

8


# Picking a row or column
If we can supply a single index, it will pick a row (i value) and return that as a rank 1 array:

In [17]:
print(a2[2]) # [7, 8, 9]

[7 8 9]


However, numpy allows us to select a single columm as well:

In [19]:
print(a2[:, 1]) # SYNTAX - numpy_array[startindex,endIndex]

[2 5 8]


<img src = "Images/Indexin_the-numpy.JPG">

For i <strong>" : " </strong> is a full slice, from start to end
<br> </br> 
For the j value take 1

<strong> Note </strong> The array you get back when you index or slice a numpy array is a view of the original array. It is the same data, just accessed in a different order. If you change the view, you will change the corresponding elements in the original array.
<br> As we saw in above example </br>

# Indexing in 3 dimensions

In [23]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])
a3

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

<img src="Images/indexing_3d.JPG">
A 3D array is like a stack of matrices:<br></br>

The first index, i, selects the matrix<br></br>
The second index, j, selects the row<br></br>
The third index, k, selects the column<br></br>
Below is the same diagram, spread out a bit so we can see the values:
<img src="images/spreaded_3d.JPG">

In [26]:
print(a3[2, 0, 1]) # 31
print("Here is how to index a particular value in a 3D array")

31
Here is how to index a particular value in a 3D array


This selects matrix index 2 (the final matrix), row 0, column 1, giving a value 31.

# Picking a row or column in a 3D array

You can access any row or column in a 3D array. There are 3 cases.<br></br>

Case 1 - Specifying the first two indices. In this case, you are choosing the i value (the matrix), and the j value (the row). This will select a specific row. In this example we are selecting row 2 from matrix 1:

In [28]:
print(a3[1, 2])

[26 27 28]


<img src = "Images/PickingA_row.JPG">


Case 2 - specifying the i value (the matrix), and the k value (the column), using a full slice (:) for the j value (the row). This will select a specific column. In this example we are selecting column 1 from matrix 0:

In [29]:
print(a3[0, :, 1])

[11 14 17]


<img src = "Images/Selecting_a_colu.JPG">

Case 3 - specifying the j value (the row), and the k value (the column), using a full slice (:) for the i value (the matrix). This will create a row by taking the same element from each matrix. In this case we are taking row 1, column 2 from each matrix:

In [30]:
print(a3[:, 1, 2]) # [15, 25, 35]

[15 25 35]


<img src = "Images/all_val.JPG">

# Picking a matrix in a 3D array

In [32]:
print(a3[2])

[[30 31 32]
 [33 34 35]
 [36 37 38]]


If we only specify the i index, numpy will return the corresponding matrix. We will call this case 1. In this example we will request matrix 2:

<strong> Case </strong>  if we specify just the j value (using a full slice for the i values), we will obtain a matrix made from the selected row taken from each plane. In this example we will take row 1:

In [33]:
print(a3[:, 1])

[[13 14 15]
 [23 24 25]
 [33 34 35]]


<img src="Images/3D-Matrix_Index.JPG">

<strong>Case </strong> if we specify just the k value (using full slices for the i and j values), we will obtain a matrix made from the selected column taken from each plane. In this example we will take column 0:

In [35]:
print(a3[:, :, 0])

[[10 13 16]
 [20 23 26]
 [30 33 36]]


<img src = "Images/3d-column-index-matrix.JPG">

# Slicing

In [37]:
a2 = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29]])
print(a2[1:,2:4])

[[17 18]
 [22 23]
 [27 28]]


This selects rows 1: (1 to the end of bottom of the array) and columns 2:4 (columns 2 and 3)

In [38]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])
print(a3[:2,1:,:2])

[[[13 14]
  [16 17]]

 [[23 24]
  [26 27]]]


# This selects:

planes :2 (the first 2 planes)
rows 1: (the last 2 rows)
columns :2 (the first 2 columns)
<img src="Images\slice_2d.JPG">

In [1]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])
print(a3[:2,1:,:2])

NameError: name 'np' is not defined

# This selects:

planes :2 (the first 2 planes)
rows 1: (the last 2 rows)
columns :2 (the first 2 columns)

<img src="Images\slicing-3d.JPG">

# More Examples

In [26]:
number = np.arange(0,48,2).reshape(2,3,4) # getting 3-d array with 2 rows, 3 col, 4 with 3rd dime
number

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[24, 26, 28, 30],
        [32, 34, 36, 38],
        [40, 42, 44, 46]]])

In [27]:
number[:,:,0] # number(martix,row,coln),
# from both matrix and all rows just select the first column

array([[ 0,  8, 16],
       [24, 32, 40]])

number(martix,row,coln), from both matrix and all rows just select the first column
":" means all values of that dimesnion,like in last example....we are trying to slice last column of both matrix. Now if you want to get only from the first matrix then you could do something like :--<strong> number[0,:,0] </strong>
<img src= "Images/three_dimension_numpy_array.PNG">

<img src = "Images/Indexing.jpg">

In [28]:
number[:,-1,-1]

array([22, 46])

In [29]:
number[0,:,-1] 

array([ 6, 14, 22])

In above example we are trying to get last column elements from first dimension matrix 

In [30]:
arr4 = np.arange(32).reshape(2,4,4)
arr4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [15]:
arr4[[[0,1,1,1],[3,2,1,0],[0,2,1,3]]] # we can have Array Indexing as well

c:\users\animeshs\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([12, 26, 21, 19])

In [31]:
# Boolean based indexing, based on condition also we can get the value
condition = arr4>5
arr4[condition]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31])

In above example, arr4>5 will store one array with bool vlaues like True and False.  True for when condition is true that is when element of arr4 is greater than5. and when pass that array, all true position index value will get printed

In [32]:
arr5 = np.arange(12).reshape(4,3)

In [33]:
arr5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
row = np.array([[0,0],[2,2]])
col = np.array([[1,1],[2,2]])
arr5[row,col] # Similar thing could be done by this as well x[[0,2],0:2]   [1:4,[1,2]] @ and [...,1] 

array([[1, 1],
       [8, 8]])

In above example we are passing the custom array that would work as indixing in numpy

In [24]:
arr6 = np.array([1,0,2,3,4,0,5,6,8])
arr6.nonzero() #to get the non-zero indexes

(array([0, 2, 3, 4, 6, 7, 8], dtype=int32),)

In [25]:
arr6_copy = np.copy(arr6) # to coppy numpy array to refrence later
arr6_copy

array([1, 0, 2, 3, 4, 0, 5, 6, 8])