In [2]:
import numpy as np

In [ ]:
# Slicing of numpy

In [3]:
number = np.arange(0,48,2).reshape(2,3,4) # getting 3d array with 2 rows, 3 col, 4 
number

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[24, 26, 28, 30],
        [32, 34, 36, 38],
        [40, 42, 44, 46]]])

In [12]:
number[:,:,0] # number(row,col,3rd dimension), from each row and column we are retreving the first element of 3rd dimension

array([[ 0,  8, 16],
       [24, 32, 40]])

In [4]:
number[:,-1,-1]

array([22, 46])

In [5]:
number[:,:,-1] #gets the last value from both row and 3 colmn of 3rd dimension

array([[ 6, 14, 22],
       [30, 38, 46]])

In [14]:
arr4 = np.arange(32).reshape(2,4,4)
arr4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [15]:
arr4[[[0,1,1,1],[3,2,1,0],[0,2,1,3]]] # we can have Array Indexing as well

c:\users\animeshs\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([12, 26, 21, 19])

In [16]:
# Boolean based indexing, based on condition also we can get the value
cond = arr4>5
arr4[cond]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31])

In [20]:
arr5 = np.arange(12).reshape(4,3)

In [21]:
arr5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
row = np.array([[0,0],[2,2]])
col = np.array([[1,1],[2,2]])
arr5[row,col] # something like this can be done as well x[[0,2],0:2]   [1:4,[1,2]] @ and [...,1] 

array([[1, 1],
       [8, 8]])

In [24]:
arr6 = np.array([1,0,2,3,4,0,5,6,8])
arr6.nonzero() #to get the non-zero indexes

(array([0, 2, 3, 4, 6, 7, 8], dtype=int32),)

In [25]:
arr6_copy = np.copy(arr6) # to coppy numpy array to refrence later
arr6_copy

array([1, 0, 2, 3, 4, 0, 5, 6, 8])