In [1]:
import numpy as np

In [2]:
height = [100,120,113,124,150,146,170,158,139] #this is list called height
weight = [45,40,52,47,58,55,80,65,51] # this is list called weight

In [3]:
x =height+weight # it just append the weight list at the end but not adding corresponding the element
print("it just append the weight list at the end but not adding corresponding the element")
print(x)

it just append the weight list at the end but not adding corresponding the element
[100, 120, 113, 124, 150, 146, 170, 158, 139, 45, 40, 52, 47, 58, 55, 80, 65, 51]


In [4]:
type(height)
type(weight)

list

In [5]:
height[::-3] # -3 denotes the stepsize, minus denotes from back. it takes every third element from end

[139, 146, 113]

In [6]:
weight

[45, 40, 52, 47, 58, 55, 80, 65, 51]

In [7]:
bmi = height/weight**2  #throws an error because mathmatical operation is not possible in list, that's why we need numpy

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [8]:
height+2 #trying to add 2 to every element in the list, but throws an error

TypeError: can only concatenate list (not "int") to list

In [9]:
height= height+2 # trying to add 2 to list numbers, but throws an error
print(height)

TypeError: can only concatenate list (not "int") to list

In [10]:
for i in range(len(height)): # to add we have do something like this

    height[i] = height[i]+2 # this is how we have to add the number to list by iterating through each element 
    print(height[i])

102
122
115
126
152
148
172
160
141


list

Now we saw limitations of list, we can overcome these limitations with numpy.

In [11]:
np_height = np.array([1,2,3,4,56,9,45,10,25])
np_weight = np.array(weight)
bmi = np_weight/np_height**2
print(bmi)

[4.50000000e+01 1.00000000e+01 5.77777778e+00 2.93750000e+00
 1.84948980e-02 6.79012346e-01 3.95061728e-02 6.50000000e-01
 8.16000000e-02]


If you see above example, we could easily do arithmetic operation on numpy

In [12]:
np_height=np_height*2 # after converting it to numpy array from list we can do mathematical operation

In [13]:
print(np_height)

[  2   4   6   8 112  18  90  20  50]


In [14]:
np_height.shape # prints the shape of array

(9,)

In [15]:
np_a = np.array([1,1,2,5,4,4,8,5])

In [16]:
np_a.shape

(8,)

In [17]:
np_a = np_a.reshape(2,4)
# To reshape the existing numpy array from np_a, we have 8 elements in np_a, so we can have, (1,8) or (8,1),(2,4) or (4,2)

In [18]:
np_a.shape

(2, 4)

In [19]:
print(np_a)

[[1 1 2 5]
 [4 4 8 5]]


In [20]:
np_b = np_a.reshape(3,2) # we will get an ValueError

ValueError: cannot reshape array of size 8 into shape (3,2)

Above example gives a value error because we have 8 elements is an array and we trying to reshape into 3*2 that would accomodate only 6 element, so all 8 element of original size can not suffice in 3*2

In [20]:
a = [(1,2), [3,4,(5)], (6,7,8)] # b[1][2] to accesss the list inside array
b = np.asarray(a)
b

array([(1, 2), list([3, 4, 5]), (6, 7, 8)], dtype=object)

In [21]:
b[1][2] #indexing to get the specific number

5

This is called slicing or indexing. You can refer list notebook post under my Python basics

In [22]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x[0:8:3])
print(x[0::3]) # syntax x(startindex:lastindex:stepsize)
# x[0::3] == x[0:8:3] == 
x[0:-1:3]#, all three will give same value, -1 indicates the last

[1 4 7]
[1 4 7]


array([1, 4, 7])

<h4>Let's check how we can have palindrome check with python indexing/Slicing concept.</h4>

In [50]:
def palindrome(s):
    return s == s[::-1]
lst = 'helleh'
palindrome(lst)

True

In [49]:
lst1 = 'Numpy'
palindrome(lst1)

False

# Below are some code examples from hackerrank, I have mentioned the url's for question. Try to solve them with concept of list, if you face any issues refer the solution below

This is one of hackerrank simple problem, link for question - https://www.hackerrank.com/challenges/apple-and-orange/problem

In [51]:
def countApplesAndOranges(s, t, a, b, apples, oranges):
    apples_count = 0
    oranges_count = 0
    for i in range(len(apples)):
        apples[i] +=a
        count = 1 if (apples[i] <= t and apples[i] >= s) else 0
        apples_count+=count
    for i in range(len(oranges)):
        oranges[i]+=b
        count = 1 if (oranges[i]<=t and oranges[i]>=s) else 0
        oranges_count+=count
    return oranges_count, apples_count
s = 7
t = 11
a = 5
b = 15
apples = [-2 ,2 ,1]
oranges = [5, -6]
x,y = countApplesAndOranges(s, t, a, b, apples, oranges)
print(x,y)


1 1


This is again one of hackerrank simple problem, link for question - https://www.hackerrank.com/challenges/between-two-sets/problem

In [26]:

def getTotalX(a, b):
    factors = []
    integers = dict()
    numbers = dict()
    for i in range(1,b[0]+1):
        integers[i] = True
        for j in range(0,len(b)):
            if(integers[i]==False):
                break
            else:
                if(b[j]%i==0):
                    integers[i] = True
                else:
                    integers[i] = False
    print(integers)
    result = dict((k, v) for k, v in integers.items() if v == True).keys()
    lst_result = list(result)
    print(lst_result)
    for i in range(0,len(lst_result)):
        numbers[i] = True
        for j in range(0,len(a)):
            if(numbers[i]==False):
                break
            else:
                if(lst_result[i]%a[j]==0):
                    numbers[i] = True
                else:
                    numbers[i] = False
    result1 = dict((k, v) for k, v in numbers.items() if v == True).keys()
    lst_result1 = list(result1)
    print(len(lst_result1))

a = [2,4]
b = [16,32,96]
getTotalX(a,b)

{1: True, 2: True, 3: False, 4: True, 5: False, 6: False, 7: False, 8: True, 9: False, 10: False, 11: False, 12: False, 13: False, 14: False, 15: False, 16: True}
[1, 2, 4, 8, 16]
3
