In [8]:
import numpy as np
height = [100,120,113,124,150,146,170,158,139] #this is list
weight = [45,40,52,47,58,55,80,65,51]
x =height+weight 
print(x) # it just append the weight list at the end but not adding corresponding the element

[100, 120, 113, 124, 150, 146, 170, 158, 139, 45, 40, 52, 47, 58, 55, 80, 65, 51]


In [9]:
type(height)
type(weight)

list

In [10]:
height[::-3] # -3 denotes the stepsize, minus denotes from back. it takes every third element from end

[139, 146, 113]

In [11]:
weight

[45, 40, 52, 47, 58, 55, 80, 65, 51]

In [12]:
bmi = height/weight**2  #throws an error because mathmatical operation is not possible in list, that's why we need numpy

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [13]:
height+2 #trying to add 2 to every element in the list, but throws an error

TypeError: can only concatenate list (not "int") to list

In [14]:
height= height+2 # trying to add 2 to list numbers, but throws an error
print(height)

TypeError: can only concatenate list (not "int") to list

In [15]:
for i in range(len(height)): # to add we have do something like this

    height[i] = height[i]+2 # this is how we have to add the number to list by iterating through each element 
    print(height[i])
type(height)

102
122
115
126
152
148
172
160
141


list

In [18]:
np_height = np.array([1,2,3,4,56,9,45,10,25])
np_weight = np.array(weight)
bmi = np_weight/np_height**2
print(bmi)

[4.50000000e+01 1.00000000e+01 5.77777778e+00 2.93750000e+00
 1.84948980e-02 6.79012346e-01 3.95061728e-02 6.50000000e-01
 8.16000000e-02]


In [20]:
np_height=np_height*2 # after converting it to numpy array from list we can do mathematical operation

In [19]:
print(np_height)

[ 1  2  3  4 56  9 45 10 25]


In [22]:
np_height.shape # prints the shape of array

(9,)

In [24]:
np_a = np.array([1,1,2,5,4,4,8,5])

In [25]:
np_a.shape

(8,)

In [26]:
np_a = np_a.reshape(2,4) # to reshape the existing numpy array from np_a, we have 8 elements in np_a, so we can have, (1,8) or (8,1),(2,4) or (4,2)

In [27]:
np_a.shape

(2, 4)

In [28]:
print(np_a)

[[1 1 2 5]
 [4 4 8 5]]


In [29]:
np_b = np_a.reshape(3,2) # we will get an ValueError

ValueError: cannot reshape array of size 8 into shape (3,2)

In [30]:
a = [(1,2), [3,4,(5)], (6,7,8)] # b[1][2] to accesss the list inside array
b = np.asarray(a)
b


array([(1, 2), list([3, 4, 5]), (6, 7, 8)], dtype=object)

In [31]:
b[1][2] #indexing to get the specific number

5

In [34]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x[0:8:3]) # SHOW WITH [0::3] as well, 
print(x[0::3]) # syntax x(startindex:lastindex:stepsize)
# x[0::3] == x[0:8:3] == x[0:-1:3], all three will give same value, -1 indicates the last

[1 4 7]
[1 4 7]


In [35]:
x = [1,2,3,4,5,6,7,8,9]
x=x+2
x

TypeError: can only concatenate list (not "int") to list

In [38]:
#this is one of hackerrank simple problem, link for question - https://www.hackerrank.com/challenges/apple-and-orange/problem

def countApplesAndOranges(s, t, a, b, apples, oranges):
    apples_count = 0
    oranges_count = 0

    for i in range(len(apples)):
        apples[i] +=a
        count = 1 if (apples[i] <= t and apples[i] >= s) else 0
        apples_count+=count
    for i in range(len(oranges)):
        oranges[i]+=b
        count = 1 if (oranges[i]<=t and oranges[i]>=s) else 0
        oranges_count+=count
    return oranges_count, apples_count
s = 7
t = 11
a = 5
b = 15
apples = [-2 ,2 ,1]
oranges = [5, -6]
x,y = countApplesAndOranges(s, t, a, b, apples, oranges)
print(x,y)


1 1


In [39]:
#this is again one of hackerrank simple problem, link for question - https://www.hackerrank.com/challenges/between-two-sets/problem
import math
def getTotalX(a, b):
    integers = dict()
    numbers = dict()
    for i in range(1,b[0]+1):
        integers[i] = True
        for j in range(0,len(b)):
            if(integers[i]==False):
                break
            else:
                if(b[j]%i==0):
                    integers[i] = True
                else:
                    integers[i] = False
    result = dict((k, v) for k, v in integers.items() if v == True).keys()
    lst_result = list(result)
    for i in range(0,len(lst_result)):
        numbers[i] = True
        for j in range(0,len(a)):
            if(numbers[i]==False):
                break
            else:
                if(lst_result[i]%a[j]==0):
                    numbers[i] = True
                else:
                    numbers[i] = False
    result = dict((k, v) for k, v in numbers.items() if v == True).keys()
    lst_result = list(result)
    return len(lst_result)

# defin a and b accordingly
res = getTotalX(a, b)


12
[1, 2, 3, 4]


In [12]:
#detail version of above code

def getTotalX(a, b):
    factors = []
    integers = dict()
    numbers = dict()
    for i in range(1,b[0]+1):
        integers[i] = True
        for j in range(0,len(b)):
            if(integers[i]==False):
                break
            else:
                if(b[j]%i==0):
                    integers[i] = True
                else:
                    integers[i] = False
    print(integers)
    result = dict((k, v) for k, v in integers.items() if v == True).keys()
    lst_result = list(result)
    print(lst_result)
    for i in range(0,len(lst_result)):
        numbers[i] = True
        for j in range(0,len(a)):
            if(numbers[i]==False):
                break
            else:
                if(lst_result[i]%a[j]==0):
                    numbers[i] = True
                else:
                    numbers[i] = False
    result1 = dict((k, v) for k, v in numbers.items() if v == True).keys()
    lst_result1 = list(result1)
    print(len(lst_result1))

a = [2,4]
b = [16,32,96]
getTotalX(a,b)

{1: True, 2: True, 3: False, 4: True, 5: False, 6: False, 7: False, 8: True, 9: False, 10: False, 11: False, 12: False, 13: False, 14: False, 15: False, 16: True}
[1, 2, 4, 8, 16]
3
